# Generated by Django 5.2.6 on 2025-09-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Base62 encoded QR code (8-10 characters)', max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product QR Code',
                'verbose_name_plural': 'Product QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
